//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_API_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageProduct
    {
        public long ImageID { get; set; }
        public string PathImage { get; set; }
        public string ImageName { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
